jobs:
  check:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Get Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./ci/ci

name: Test

on:
  schedule:
    - cron: "50 2/3 * * *"
